spring.application.name=bai2
#config logging
logging.level.root=warn
logging.level.com.example.bai2.controller=info
logging.level.com.example.bai2.service=info
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n
